// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6H7hLjOUYE2uPh1hfAUdXwMpwzQ4NoJ8',
    appId: '1:760077084527:web:dd90099ebc8904eade2a9a',
    messagingSenderId: '760077084527',
    projectId: 'crashlytics-1c592',
    authDomain: 'crashlytics-1c592.firebaseapp.com',
    storageBucket: 'crashlytics-1c592.appspot.com',
    measurementId: 'G-5TR0TRZRD5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoPqz-A9w6LrhiCYD8exiOMIIGNqrB7tM',
    appId: '1:760077084527:ios:61f340f82b599c8ede2a9a',
    messagingSenderId: '760077084527',
    projectId: 'crashlytics-1c592',
    storageBucket: 'crashlytics-1c592.appspot.com',
    iosBundleId: 'com.example.crashlyticsPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoPqz-A9w6LrhiCYD8exiOMIIGNqrB7tM',
    appId: '1:760077084527:ios:61f340f82b599c8ede2a9a',
    messagingSenderId: '760077084527',
    projectId: 'crashlytics-1c592',
    storageBucket: 'crashlytics-1c592.appspot.com',
    iosBundleId: 'com.example.crashlyticsPoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6H7hLjOUYE2uPh1hfAUdXwMpwzQ4NoJ8',
    appId: '1:760077084527:web:70ea03d54aa906dade2a9a',
    messagingSenderId: '760077084527',
    projectId: 'crashlytics-1c592',
    authDomain: 'crashlytics-1c592.firebaseapp.com',
    storageBucket: 'crashlytics-1c592.appspot.com',
    measurementId: 'G-P52TYPFNJD',
  );

}